#!/bin/sh

set -eux

set -a
# shellcheck disable=SC1091
. "$(pwd)/config.env"
set +a

# Configure logging
install_logfile="/tmp/immich-install.log"
exec >> "$install_logfile" 2>&1

echo "Running postinstall as $(whoami)"

# Install prebuilt VectorChord extension into PostgreSQL
"$(pwd)/installvectorchord.sh"

# Build Immich application
"$(pwd)/configureimmich.sh"

# Install Launchd daemons
"$(pwd)/installdaemons.sh"
